name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - qa-login

jobs:
  build_and_preview:
    environment: preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci --force
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: coara-tech-tests
          channelId: qa-login
